name: Issue Event Details
on:
  issues:
    types: [opened, edited, closed]
jobs:
  print_event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Sender: ${{ github.event.sender.login }}"
